import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import XIcon from "./components/XIcon";
import LinkedinIcon from "./components/LinkedinIcon";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="flex flex-col w-screen h-screen items-center justify-center bg-cover bg-center bg-no-repeat relative text-gray-800"
          style={{ backgroundImage: "url('/montery.jpg')" }}
        >
          <div className="absolute inset-0 bg-black/30" />

          <div className="flex bg-white rounded-lg p-8 relative z-10 shadow-lg">
            {children}
          </div>
          <div className="absolute bottom-4 right-4 px-4 py-2 text-center text-base bg-gray-200 rounded-lg shadow-lg font-semibold flex gap-6">
            <span className="flex items-center gap-2">
              <LinkedinIcon className="w-6 h-6 text-blue-500" />
              /nikolajhoggins
            </span>
            <span className="flex items-center gap-2">
              <XIcon className="w-6 h-6" />
              @hogginsio
            </span>
          </div>
        </div>
      </body>
    </html>
  );
}
